### PR TITLE
Bug fixes round 3

### LINKED ISSUE #149: Title case in a few places
### Describe the bug

- [x] Chips in java onboarding menu 
image
- [x] Select Updatable on instance menu
image
- [x] Clear Filters in Browse tab
image
- [x] Modrinth Website on version pages
image

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thesuzerain**
Fixes #149 #150 #156  #157 #165  #173 #176 #177 #189  #203 #211 #212 #224 #230 #265 #269 #270

### CODE REVIEW

**Review by a-person1908 — APPROVED** [review]

File: theseus/src/api/profile.rs [hunk 1]
```diff
@@ -71,6 +68,28 @@ pub async fn get(
     Ok(profile)
 }
 
+/// Gets all projects version metadata for a profile
+/// Allows loading metadata without loading all project data
+#[tracing::instrument]
+pub async fn get_projects_metadata(
+    path: &Path,
+) -> crate::Result<Option<HashMap<PathBuf, ProjectMetadata>>> {
```
Comment (Geometrically) [inline theseus/src/api/profile.rs:76]: what is this used for?

File: theseus/src/state/profiles.rs [hunk 2]
```diff
@@ -375,6 +377,21 @@ impl Profile {
...
+            &state.io_semaphore,
+            &state.fetch_semaphore,
+        )
+        .await?;
+        let mut new_profiles = state.profiles.write().await;
+        if let Some(profile) = new_profiles.0.get_mut(&self.path) {
+            for (path, project) in synced_projects {
+                profile.projects.insert(path, project);
+            }
+        }
```
Comment (Geometrically) [inline theseus/src/state/profiles.rs:394]: we should not do this imo, the debouncer already watches this

File: theseus_gui/src/pages/Browse.vue [hunk 3]
```diff
@@ -267,11 +267,30 @@ async function onSearchChange(newPageNumber) {
...
+    if (el === searchWrapper.value) {
+      console.log(`Element name (IS searchWrapper): ${el.nodeName}, id: ${i}`)
+    }
+    if (el.scrollHeight > el.clientHeight && el.scrollTop > 0) {
+      console.log(`Element name: ${el.nodeName}, id: ${i}, scroll: ${el.scrollTop}`)
+    }
+  }
+  console.log(document.querySelectorAll('div'))
+  console.log(searchWrapper.value)
+  console.log(searchWrapper.value.scrollTop)
```
Comment (Geometrically) [inline theseus_gui/src/pages/Browse.vue:285]: what is the point of this?

File: theseus_gui/src/pages/Browse.vue [hunk 4]
```diff
@@ -355,6 +374,33 @@ const sortedCategories = computed(() => {
...
+      } else {
+        // One is a number and one is a string, numbers go first
+        let numStringComp = isNaN(aNum) ? 1 : -1
+        if (numStringComp != 0) return numStringComp
+      }
+    }
+    return 0
+  })
+  return sortable
+}
```
Comment (Geometrically) [inline theseus_gui/src/pages/Browse.vue:402]: what is this used for?

File: theseus_gui/src/pages/Browse.vue [hunk 5]
```diff
@@ -818,6 +868,9 @@ const showLoaders = computed(
 
 .search-container {
   display: flex;
+  height: 100%; /* takes up only the necessary height */
+  overflow-y: auto;
+  scroll-behavior: smooth;
```
Comment (Geometrically) [inline theseus_gui/src/pages/Browse.vue:873]: why is this needed? iirc it already is scrollable

File: theseus_gui/src/pages/project/Index.vue [hunk 6]
```diff
@@ -344,16 +348,17 @@ const markInstalled = () => {
...
       instance.value.path,
-      Object.entries(instance.value.projects)
+      Object.entries(metadatas.value)
         .map(([key, value]) => ({
           key,
           value,
         }))
-        .find((p) => p.value.metadata?.version?.project_id === data.value.id).key
+        .find((p) => p.value.version?.project_id === data.value.id).key
     )
```
Comment (Geometrically) [inline theseus_gui/src/pages/project/Index.vue:362]: why was this needed? the instance projects are already available

File: theseus_gui/src/pages/instance/Mods.vue [hunk 7]
```diff
@@ -155,21 +155,16 @@
...
-            v-tooltip="'Update project'"
-            :disabled="!mod.outdated"
-            icon-only
-            @click="updateProject(mod)"
-          >
-            <UpdatedIcon v-if="mod.outdated" />
-            <CheckIcon v-else />
+          <Button v-else :disabled="!mod.outdated" icon-only @click="updateProject(mod)">
+            <UpdatedIcon v-if="mod.outdated" v-tooltip="'Update project'" />
+            <CheckIcon v-else v-tooltip="'Fully updated'" />
```
Comment (Geometrically) [inline theseus_gui/src/pages/instance/Mods.vue:160]: imo this tooltip should just say updated

File: theseus_gui/src/pages/project/Index.vue [hunk 8]
```diff
@@ -207,7 +207,8 @@
         :dependencies="dependencies"
         :install="install"
         :installed="installed"
-        :installed-version="installedVersion"
+        :installing="installing"
+        :installedVersion="installedVersion"
```
Comment (Geometrically) [inline theseus_gui/src/pages/project/Index.vue:211]: kebab case needed here

File: theseus_gui/src/components/ui/AccountsCard.vue [hunk 9]
```diff
@@ -4,7 +4,7 @@
     ref="button"
     class="button-base avatar-button"
     :class="{ expanded: mode === 'expanded' }"
-    @click="showCard = !showCard"
+    @click="toggleShow()"
```
Comment (Geometrically) [inline theseus_gui/src/components/ui/AccountsCard.vue:7]: I don't think the issue mentioned is worth fixing, deleting accounts is a low cost action (someone can just log back in). I think we should revert the changes in this file

File: theseus_gui/src/pages/Browse.vue (hunk 3 above)
Comment (thesuzerain) [reply theseus_gui/src/pages/Browse.vue:285]: This one is a mistakenly left in console.logging for testing the div elements for #230

File: theseus_gui/src/pages/Browse.vue (hunk 4 above)
Comment (thesuzerain) [reply theseus_gui/src/pages/Browse.vue:402]: This one is for #269

File: theseus_gui/src/pages/Browse.vue (hunk 5 above)
Comment (thesuzerain) [reply theseus_gui/src/pages/Browse.vue:873]: see disc

File: theseus/src/api/profile.rs (hunk 1 above)
Comment (thesuzerain) [reply theseus/src/api/profile.rs:76]: See below comment for "the instance projects are already available"

File: theseus_gui/src/pages/project/Index.vue (hunk 6 above)
Comment (thesuzerain) [reply theseus_gui/src/pages/project/Index.vue:362]: The instances are available but the version subfields are not, because when the instances are fetched the 'clear' field is passed as true to not load/reload all project data into memory, but those versions are needed for this. 

However I just double checked the backend and I think I missed how little data is contained in the projects that is not in the metadata, so it might be worth just flipping the true to a false so that all project data is loaded (or change it from only getting metadatas to only getting versions)

**Review by Geometrically — APPROVED** [review]
