### PR TITLE
Beta bugs

### LINKED ISSUE #442: Extremely High CPU, Disk, and Memory Usage when importing instances
### Describe the bug

I imported 2 instances from Prism Launcher but the importing of instances doesnt limit usage so it makes my computer unusable

### Steps to reproduce

1. Import a somewhat large instance into the launcher

### Expected behavior

limit the usage of the program so i doesn't break your computer

### Additional context

image

### LINKED ISSUE #467: The image in onboarding can be selected as if it was text
### Describe the bug

image

### Steps to reproduce

1. Start the App for the first time
2. Try and select the onboarding image

### Expected behavior

The image can't be highlighted like this

### Additional context

Running on Windows 10

### LINKED ISSUE #490: Latest version of mod is hidden when trying to install it
### Describe the bug

_No response_

### Steps to reproduce

1. Click on the `Install` button
2. Open versions list
3. The latest will be hidden

### Expected behavior

Visible the latest version in select menu

### Additional context

_No response_

### LINKED ISSUE #492: Deleting instances in rapid succession doesn't work
### Describe the bug

If you delete many instances in a short timespan, they will stop being able to get deleted.

### Steps to reproduce

1. Go to library tab
2. Begin right clicking and deleting instances
3. Repeat ~3-4 times
4. Bug occurs

### Expected behavior

The instances will all get deleted

### Additional context

The 3rd or 4th instance (may depend on rate at which they were deleted) stays in the library and cannot be deleted until the library is reopened by the user. I may not have made it obvious but instances that also weren't attempted to be deleted in the initial steps to produce also can't be deleted after the bug occurs.

### LINKED ISSUE #499: Installing a modpack that have options for multiple modloaders, then updating it might break the instance
### Describe the bug

On some modpacks (like Adrenaline), the fabric and quilt versions are the same. The issue comes when you try to update a quilt modpack that also has a fabric version. Instead of only quilt-to-quilt updates, Modrinth app might update the modpack to fabric instead, and if the user added a quilt-only mod like Ok Zoomer, the instance breaks.

### Steps to reproduce

1. Click Browse, go to Adrenaline.
2. Click Versions
3. Select a quilt version and install it
4. Go to the installed instance.
5. Click Update Modpack
6. Issue Appears (quilt changed to fabric)

### Expected behavior

I think the ideal behaviour would be that if it was the latest quilt version, it would not update, and if it was not the latest same modpack version but still using quilt , it would update to the latest quilt version. However what happens is that it updates to a fabric version instead.

### Additional context

_No response_

### LINKED ISSUE #502: Scrolling away from end of live log makes it stop automatically scrolling down until reopen
### Describe the bug

When you open the live log, it automatically scrolls down as more lines are printed to it, and when you scroll up, it stops doing so. However, it doesn't resume scrolling down if you scroll back down to the end of the log.

### Steps to reproduce

1. Start an instance
2. While it's starting, go to the logs tab and choose live log
3. Scroll up
4. Scroll back down to the end
5. See issue

### Expected behavior

The log window continues scrolling down as more lines appear.

### Additional context

_No response_

### LINKED ISSUE #504: YOSBR mod does not copy options.txt
### Describe the bug

The mod YOSBR does not work fully as intended with Modrinth app. I've filed the issue here and not [in the mod's repo](https://github.com/shedaniel/your-options-shall-be-respected) because it works as intended with other launchers, such as CurseForge, Prism, MultiMC, GDLauncher...

### Steps to reproduce

1. Install Modrinth app
2. Create a Fabric instance (e.g. 1.20.1)
3. Click -> Add content -> search "[YOSBR](https://modrinth.com/mod/yosbr)" on Mods -> Install
4. Go back to home -> right click the instance -> Open folder
5. Create folder "config", inside that "yosbr", inside that text file "options.txt"
6. Open the text file and write [an option](https://minecraft.fandom.com/wiki/Options.txt) that can easily be tested for, e.g. `guiScale:1`
7. Run the instance

### Expected behavior

Expected the GUI scale to be 1, as the options.txt file should be copied to root folder by the mod. That, however, does not work.

### Additional context

YOSBR can also copy mod config files (not described here), this seems to work.

FYI, this issue is also present on Pojav Launcher, but there at least the options.txt is intentionally overridden to support mobile phones better. In Modrinth app, this is obviously not the goal, so it is a valid bug.

### LINKED ISSUE #506: When using the mod browser to install mods into a instance, "installed" button reverts to "Install"
### Describe the bug

When you change page on the mod browser when making a instance, changing page on the browser will reset the previous page. e.g mods that have been installed on the prior page show up as, "install" implying they are not installed. 

### Steps to reproduce

1. make a instance
2. go to the mod browser
3. install a mod
4. change the page
5. go back to prior page
6. bug occurs

### Expected behavior

The mods that are installed should still display as installed even when changing pages.

### Additional context

When you click the bugged install button it doesn't download the same mod again thankfully and will display "installed" after clicked.

Note: this is after a fresh install from latest

System info:
Operating system, Windows 11 Pro build 22621 
Cpu: AMD Ryzen 5 5500, 3600 Mhz
Gpu: Gtx 1050ti

### LINKED ISSUE #509: Add content page doesn't display downloaded mods correctly after switching pages
### Describe the bug

I updated to version 0.4.0 today and wanted to add some mods to the existing pack i had already made, problem was that when i went to add more mods, after switching to page 2, every mod displayed as not installed, even though some where installed, so i tested if it was an issue with existing packs from previous versions of the launcher and created a test pack with only sodium and iris installed, but same thing happened, after switching page and switching back to page 1, they both showed up as not installed, even though they were installed. 

I also only installed the mods through the add content button in the launcher, not through files.

I'm on a Windows 11 laptop on 22H2 if that helps and my packs were on both fabric and quilt loaders respectively but both of them had the issue.

**Video below of issue**
https://github.com/modrinth/theseus/assets/95070196/70a8f7a1-cdc4-490f-ae55-02b51d15bffd

### Steps to reproduce

1. Create or go into an existing pack you've made
2. Click the "Add Content" button and look for mods you've already installed
3. Switch pages and see if they still say installed

### Expected behavior

Every mod that is installed into the pack should show as installed while searching for mods to add

### Additional context

I've had no such issue before on the previous versions of the launcher, just started happening after updating to ver 0.4.0 of the launcher

### LINKED ISSUE #512: Categories are not sorted by they name
### Describe the bug

On the Library page, the Categories for the instance are not sorted by they name, but by the name of first instance inside them.
Is could be worse if the instance start by a number: the 'unamed category' will be move below the category containing the numeral instance.

#### Category  wrong sort
1. Create a instance `AA` with the category `Zcat`
2. Create a instance `ZZ` with the category `Acat`
3. Got to the library page
4. See error: The category "Zcat" is before "Acat"

#### 'unamed category' below a named one
1. Create a instance `BB` with no category
3. Create a instance `00` with the category `Bcat`
4. Got to the library page
5. See error: The instance "BB" is below the category "Bcat"

### Expected behavior

The category will be sorted in the alphabetical order of they own name.
And the 'unamed category' will be always the first.

### Additional context

App version 0.4.0
Windows 10

### LINKED ISSUE #518: UI selecting non-text
### Describe the bug

When dragging the app, or selecting text in the app, you are able to select non-text elements including images and boxes. This appears to be outside of the expected behaviour and usually on desktop apps you cannot select any text except text that you may specifically need to copy (e.g. ids, tokens) and of course in text input fields.

image

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #519: Cannot import packs created from Launcher with Quilt Loader
### Describe the bug

I've created a pack that has all the mods I want on Quilt and have exported it using the launcher's export feature, but every time I try to import it on another pc, I get the error that the loader ver is invalid, tried this on multiple loader versions however, I sill get the same "invalid loader ver" error. 

PS: This is an old bug that still happened in launcher ver 0.2.0 and 0.3.0.

**Screenshot showing that the launcher has the loader version I used when exporting pack**
quilt loader version

**Video showcasing issue below**
https://github.com/modrinth/theseus/assets/95070196/bce48e2b-472a-43fd-855f-2814dc670229

### Steps to reproduce

1. Create a pack with Quilt and choose the loader version you want
2. Add the mods you want from the "Add Content" button
3. Export the pack using the launcher
4. Try importing that same pack after exporting it
5. Encounter error

### Expected behavior

Importing should not fail as you can recreate the same pack in the launcher from scratch and have it works fully without an import

### Additional context

I've tried with both loader versions 0.17.9-beta 1 and 0.20.0-beta 11 so far with both having this issue

### LINKED ISSUE #524: Dependencies not downloaded when creating an Instance from a mod with Dependencies
### Describe the bug

Dependencies are not downloaded when starting a new instance with a mod that has dependencies. Removing that mod and redownloading via the Add content button for the instance downloads the dependencies correctly. 

### Steps to reproduce

1. Search a mod that has dependencies (In my case, I used my mod MCDoom)
2. Click Install and create a new instance. 
3. Instance only has the selected mod with no dependencies installed/listedInstall

### Expected behavior

Installs dependencies when creating the instance. 

### Additional context

_No response_

### LINKED ISSUE #531: Middle clicking on dependency of project opens new window tauri.localhost
### Describe the bug

Title
image

### Steps to reproduce

1. Go to project versions page.
2. Click on version.
3. Middle-click on dependency.
4. New window with title "tauri.localhost" opens up.

### Expected behavior

Nothing

### Additional context

Windows 11
Modrinth app 0.5.0

### LINKED ISSUE #538: SoftLock when clicking the open in browser button in a image.
### Describe the bug

You cant do nothing, and you must kill the task to procced.
6DFBczb
(The second button)

### Steps to reproduce

Go to the gallery of a mod.
Click an image.
Click open in browser.
Get softlocked.

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #553: PrismLauncher modpack importer doesn't detect non-default instances folder
### Describe the bug

When non-default instance folder is specified in PrismLauncher settings, Modrinth App doesn't detect it.
It correctly detects the PrismLauncher Path itself (at `/home/user/.local/share/PrismLauncher/`) but then checks default `instances` subfolder.

Instance folder can be located in `prismlauncher.cfg` file, at `InstanceDir`

I also suspect this is the case with MultiMC but I haven't tested myself.

### Steps to reproduce

1. Go to "Create Instance", select "Import From Launcher", select PrismLauncher.
2. PrismLauncher Path detected, but no instances are shown.

### Expected behavior

Instances from their actual location are shown.

### Additional context

If I select parent folder of my actual `instances` folder as "PrislLauncher Path", I can see all the instances

### LINKED ISSUE #554: Disable Analytics option not saving
### Describe the bug

When I turn on the disable analytics option, and go to another menu, the option turns off.
image

### Steps to reproduce

Go to settings.
Enable "Disable Analytics".
Go to llibrary
Return to settings.

Option didnt save.

### Expected behavior

The expected behavior should be that the option still enabled.

### Additional context

OS: Windows10 22h2
Version: Lastest

### PR DESCRIPTION
**Pull request by thesuzerain**
Fixes #442 (doesnt entirely remove CPU usage- there are spikes- but drastically improves)
Fixes #467 
Fixes #490 
Fixes #492 
Fixes #499 
Fixes #502 
Fixes #504  (as long as the options.txt override settings arent selected)
Fixes #506 
Fixes #509 
Fixes #512 
Fixes #518 
Fixes #524 
Fixes #538 
Fixes #519 
Fixes #531 
Fixes #553 
Fixes #554

### CODE REVIEW

File: theseus/src/api/profile/mod.rs [hunk 1]
```diff
@@ -1043,18 +1043,26 @@ pub async fn create_mrpack_json(
...
-        None => s,
+fn sanitize_loader_version_string(s: &str, loader: PackDependency) -> &str {
+    match loader {
+        // Split on '-'
+        // If two or more, take the second
+        // If one, take the first
+        // If none, take the whole thing
+        PackDependency::Forge
+        | PackDependency::FabricLoader
+        | PackDependency::Minecraft => {
```
Comment (triphora) [inline theseus/src/api/profile/mod.rs:1054]: I don't actually see why this should be done for any pack dep other than Forge. For Minecraft, we don't want 1.19.4-rc1 being turned into 1.19.4. For Fabric, I don't think they even use dashes at all. So really this should just be a special case for Forge.

File: theseus/src/api/pack/import/atlauncher.rs [hunk 2]
```diff
@@ -107,10 +100,35 @@ pub async fn is_valid_atlauncher(instance_folder: PathBuf) -> bool {
...
+                    return "".to_string();
+                } else {
+                    tracing::warn!(
+                        "Could not read existing instance.json at {}: {}",
+                        instance_folder.display(),
+                        e
+                    )
+                };
+                "".to_string()
+            });
```
Comment (Geometrically) [inline theseus/src/api/pack/import/atlauncher.rs:119]: is this meant to be removed?

File: theseus/src/api/profile/mod.rs (hunk 1 above)
Comment (Geometrically) [reply theseus/src/api/profile/mod.rs]: agreed

File: theseus/src/launcher/mod.rs [hunk 3]
```diff
@@ -462,27 +462,24 @@ pub async fn launch_minecraft(
...
+            if !re.is_match(&options_string) {
+                // The key was not found in the file, so append it
+                options_string.push_str(&format!("\n{}:{}", key, value));
+            } else {
+                let replaced_string = re
+                    .replace_all(&options_string, &format!("{}:{}", key, value))
+                    .to_string();
+                options_string = replaced_string;
+            }
         }
```
Comment (Geometrically) [inline theseus/src/launcher/mod.rs:479]: if someone has an existing options.txt, it should add to it, not override it

File: theseus/src/state/mod.rs [hunk 4]
```diff
@@ -345,27 +345,25 @@ pub async fn init_watcher() -> crate::Result<Debouncer<RecommendedWatcher>> {
     let (mut tx, mut rx) = channel(1);
 
     let file_watcher = new_debouncer(
-        Duration::from_secs_f32(2.0),
+        Duration::from_secs_f32(10.0),
```
Comment (Geometrically) [inline theseus/src/state/mod.rs:348]: 10 seconds is very long for the profile syning, mods will take forever to add. what was the reason for this change?

**Review by triphora — APPROVED** [review]

File: theseus/src/state/profiles.rs [hunk 5]
```diff
@@ -840,12 +839,17 @@ impl Profiles {
...
                             new_profiles.0.get_mut(&profile_path)
                         {
-                            if let Some(recent_version) = versions.get(0) {
+                            let loader = profile.metadata.loader;
+                            let recent_version = versions.iter().find(|x| {
+                                x.loaders
+                                    .contains(&loader.as_api_str().to_string())
+                            });
+                            if let Some(recent_version) = recent_version {
                                 profile.modrinth_update_version =
```
Comment (Geometrically) [inline theseus/src/state/profiles.rs:853]: we should just get rid of modrinth_update_version IMO. it's pointless, the frontend should be able to pick which modpack version they want to install

File: theseus/src/state/projects.rs [hunk 6]
```diff
@@ -297,10 +297,22 @@ pub async fn infer_data_from_files(
...
+            let bytes_read =
+                file.read(&mut buffer).await.map_err(IOError::from)?;
+            if bytes_read == 0 {
+                break;
+            }
+            hasher.update(&buffer[..bytes_read]);
+        }
+
+        // slight sleep to lessen cpu load
+        tokio::time::sleep(Duration::from_nanos(10)).await;
```
Comment (Geometrically) [inline theseus/src/state/projects.rs:313]: does this actually do anything? I wouldn't expect it to

File: theseus_gui/src/pages/Settings.vue [hunk 7]
```diff
@@ -311,7 +311,16 @@ async function refreshDir() {
...
+        <Toggle
+          id="opt-out-analytics"
+          :model-value="settings.opt_out_analytics"
+          :checked="settings.opt_out_analytics"
+          @update:model-value="
+            (e) => {
+              settings.opt_out_analytics = e
+            }
+          "
+        />
```
Comment (Geometrically) [inline theseus_gui/src/pages/Settings.vue:323]: why was this changed?

File: theseus_gui/src/components/ui/IncompatibilityWarningModal.vue [hunk 8]
```diff
@@ -165,5 +165,9 @@ td:first-child {
   flex-direction: column;
   gap: 1rem;
   padding: 1rem;
+
+  :deep(.animated-dropdown .options) {
+    max-height: 13.375rem;
+  }
```
Comment (Geometrically) [inline theseus_gui/src/components/ui/IncompatibilityWarningModal.vue:171]: what's this used for

**Review by Geometrically — CHANGES_REQUESTED** [review]

File: theseus/src/api/pack/import/atlauncher.rs (hunk 2 above)
Comment (thesuzerain) [reply theseus/src/api/pack/import/atlauncher.rs:119]: I meant it to be included so that if the person in disc who's bug I couldn't replicate could have a log when they tried to import their profiles that should be importable.

That being said I do have a guess for what the issue was and fixed it, so I can revert this

File: theseus/src/state/mod.rs (hunk 4 above)
Comment (thesuzerain) [reply theseus/src/state/mod.rs:348]: was trying to reduce cpu load on installs, (when many packs are imported one after another). Reverted as I don't think this is the biggest impact change I made

File: theseus_gui/src/pages/Settings.vue (hunk 7 above)
Comment (thesuzerain) [reply theseus_gui/src/pages/Settings.vue:323]: For issue 554. Updated list to include it

File: theseus_gui/src/components/ui/IncompatibilityWarningModal.vue (hunk 8 above)
Comment (thesuzerain) [reply theseus_gui/src/components/ui/IncompatibilityWarningModal.vue:171]: Issue 490

File: theseus/src/launcher/mod.rs (hunk 3 above)
Comment (thesuzerain) [reply theseus/src/launcher/mod.rs]: Fixed something in it separate to this comment.

currently if an options.txt exists, this loads it, replaces relevant values, adds relevant new ones, and writes back to file. It doesn't override the file, only the chosen options and writes it back. Unless you mean it shouldn't overwrite the option but should add an additional one (ie: two entries for fullscreen) in which case I may be misunderstanding

File: theseus/src/api/profile/mod.rs (hunk 1 above)
Comment (thesuzerain) [reply theseus/src/api/profile/mod.rs]: Done, makes sense

**Review by Geometrically — APPROVED** [review]
