### PR TITLE
Bug fixes

### LINKED ISSUE #230: Going to next page/changing filters should scroll to the top
### Describe the bug

Upon changing a filter or page, the modrinth website scrolls to the top, while Theseus stays at the same place

https://github.com/modrinth/theseus/assets/37855219/6915e1cc-fff2-437b-8f5b-d575c87ecbe0

### Steps to reproduce

1. go to any project browser
2. scroll to bottom of page
3. click next page or change filter

### Expected behavior

It should scroll back to the top

### Additional context

_No response_

### LINKED ISSUE #234: Off-platform ResourcePacks don't go in their tab
### Describe the bug

Resource packs not from modrinth don't show up in the resource packs tab.

### Steps to reproduce

1. create a new instance
2. open it's folder and put a resource pack inside
3. observe how the resource pack is displayed inside of "All", and a new "Other" tab has appeared
4. add a resource pack using the Add content button
5. observe how the off-platform resource pack doesn't exist inside the new "resource packs" tab

image

image

### Expected behavior

All resourcepacks, regardless of origin, are displayed in the resourcepacks tab

### Additional context

_No response_

### LINKED ISSUE #237: Multiple installs of the same mod
### Describe the bug

Theseus sometimes installs multiple versions of the same mod.

### Steps to reproduce

1. Install 2 mods with different versions of the same dependency.

### Expected behavior

Theseus should either prompt the user to decide what dependency they want, or install the latest version of the dependency automatically (probably worse).

### Additional context

_No response_

### LINKED ISSUE #290: Cannot install two versions of the same modpack.
### Describe the bug

Having installed a 1.20.1 version of a modpack, trying to download a 1.19.4 version of the same modpack seems to not work, getting stuck on the 1st screenshot's screen. 
image
When exited from the ''stuck'' installation screen, going to the library shows this. One modpack loading, the other one still working.
image

### Steps to reproduce

1. Install any modpack.
2. Go to the same modpack's ''Browse'' tab.
3. Click ''Versions'', choose another version of the same modpack.
4. Click ''Install''

### Expected behavior

When pressing ''Install'', app gets stuck on the screen provided in the 1st screenshot.

### Additional context

_No response_

### LINKED ISSUE #313: Updating mods breaks the UI
### Describe the bug

When pressing the update button, the spinning Modrinth icon will not go away/the shown version doesn't update(the file does get updated in the background). In this state, the Home/Library buttons stop functioning at all.

https://github.com/modrinth/theseus/assets/5133936/744fbf50-0e23-4935-8a58-1da4fde9b662

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #382: Folder button broken.
### Describe the bug

Whenever i click on the folder button on my modpack, It doesn't send me to the instance's folder, It just sends me to the main menu of the files home screen.

### Steps to reproduce

1. Go to your modpack instance.
2. Click the folder button on your modpack.

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #388: The "Export modpack" dialog doesn't follow the advanced rendering option
### Describe the bug

If advanced rendering is disabled the modpack export dialog will still use blur.

### Steps to reproduce

1. Go to settings and disable advanced rendering
2. Go to an instance and press "Export modpack"

### Expected behavior

No blur effect is applied to the background

### Additional context

_No response_

### LINKED ISSUE #396: importing does not work (mod folder remains empty)
### Describe the bug

I exported a profile I created, with which I wanted to play with friends. Before getting them involved, I tested importing the profile myself, but the imported profile was empty. Then I proceeded with deleting it and accidentally deleted my actual profile in which I put lots of work, but that’s another story.
I do not know whether this happens only on my pc or is a general problem, but it is a huge one in my opinion. Not only because I lost a save in which I poured lots of my time.

### Steps to reproduce

Export a profile.
Import the profile.

### Expected behavior

After importing, I expected the mods and the shader to be there.

### Additional context

Launcher Version: 0.3.0

### LINKED ISSUE #399: "/" in modpack and new instances are a problem.
### Describe the bug

naming new instances with a slash in it will create a new folder inside the profile folder there for breaking it causing no mods to load (this includeing downloading modpacks with a "/" in the name.

### Steps to reproduce

1. be on the newest version of modrinth launcher 
2. create a new instance with a "/" in the name with a word after it or not
3. after creation open up the folder or manually find the file location
4. open the file and inside you should see a new folder with the name of whatever was on the other side of the "/"

### Expected behavior

you should see a new folder with the name of whatever was on the other side of the "/" for example 
naming a new instance "cat/dog" and creating it the profile file will be called "cat" while the folder in side will be called "dog"

with a mod pack for example if called "cat/dog" same thing would apply but all the mods will appear in a mods folder inside of the "dog" file rendering the modpack unable to be played it just loads up  the default loader.

### Additional context

_No response_

### LINKED ISSUE #400: Fullscreen Config Doesn't Seem To Save
### Describe the bug

For some reason, while I can go into settings and 'change' the launch fullscreen option, it doesn't actually save. For some strange reason, if I come back it will say it's unselected despite just selecting it.

### Steps to reproduce

Select fullscreen. Go into any other Modrinth window (?) and then return to settings.

### Expected behavior

I would expect the option to save and launch Minecraft maximized. And not revert back the moment I look away, literally.

### Additional context

image

### LINKED ISSUE #407: Updating a mod within a existing modpack crashes the client.
### Describe the bug

When you click the "refresh" button that's the update button behind a mod, it keeps endlessly loading with the Modrinth causing the whole application to enter into some freezed state. the buttons do still animate but nothing functions anymore and you must terminate the application through Task Manager.

Funnily enough the one mod you wanted to update still updated, if you try to update any other mods they simply don't update, then you restart the application update the other mod, restart the application again because the issue continues to come back each time. Issue #393 seems to be semi the same, but I don't have to start a Minecraft instance for it to occur.

I been having this issue since 0.2.0, and thought somebody else must've had this too but seeing it's still existent I've decided to do the reporting myself.

### Steps to reproduce

1 > Head to your desired modpack
2 > Update a mod, see the infinite loading logo, be patient but after 10 minutes give up
3 > Check if file has updated which it has
4 > Kill the application through taskmanager as pressing the X button doesn't function
5 > Repeat step 1-4 to update the next mod, which repeats the issue.

### Expected behavior

Expected behavior is for the app to recognize that it has updated the file, and allow the user to continue updating the other mods, same applies to updating all mods it only updates 1 of all the selected mods and proceeds to completely freeze up, as if it doesn't know the file updated.

### Additional context

Software:
Windows 10 22H2 
OS Build: 19045.3208

Hardware:
RTX 3080
Ryzen 7800X3D
32GB DDR5 6000MHZ

I can't find any logs, and I already cleaned my theseus folder to regenerate it to see if it had any corruptions, this didn't fix my problem.

The launcher app doesn't co-exist on the same drive as the #appdata# folder, but this shouldn't be a problem I believe?

### PR DESCRIPTION
**Pull request by thesuzerain**
Fixes #230 
Fixes #234 
Fixes #290 
Fixes #313 
Fixes #382 
Fixes #388 
Fixes #396 
Fixes #399 
Fixes #400 
Fixes #407 

Fixes permissions in Info.plist for voice chat on Mac
Fixes deadlock preventing app closing via safeprocesses
Potential fix for title bar issues

### CODE REVIEW

File: theseus/src/state/projects.rs [hunk 1]
```diff
@@ -138,6 +160,44 @@ pub struct Dependency {
     pub dependency_type: DependencyType,
 }
 
+impl Dependency {
+    // As Modrinth doesn't always provide the project ID, we have to infer it from the version ID
+    pub async fn populate(&mut self) -> crate::Result<()> {
+        let mut dep = self;
```
Comment (Geometrically) [inline theseus/src/state/projects.rs:166]: this IMO is a pretty bad way of solving this specific issue. I think you can remove the fix for this GH issue and I can fix this one

File: theseus_gui/src-tauri/src/api/profile.rs [hunk 2]
```diff
@@ -103,6 +104,47 @@ pub async fn profile_check_installed(
...
+                        && dependency.project_id == Some(project.id.clone())
+                    {
+                        duplicates.push(dependency.clone());
+                    }
+                })
+            }
+        });
+    }
+    Ok(duplicates)
+}
```
Comment (Geometrically) [inline theseus_gui/src-tauri/src/api/profile.rs:146]: See above. Don't like this fix (quite a lot of code smell imo). I'll fix this in my auth PR so I think this can be removed from this PR

File: theseus_gui/src/helpers/profile.js [hunk 3]
```diff
@@ -59,6 +59,13 @@ export async function check_installed(path, projectId) {
   return await invoke('plugin:profile|profile_check_installed', { path, projectId })
 }
 
+export async function check_duplicate_nonversional_dependencies(path, dependencies) {
+  return await invoke('plugin:profile|profile_get_installed_duplicate_nonversional_dependencies', {
+    path,
+    dependencies,
+  })
+}
```
Comment (Geometrically) [inline theseus_gui/src/helpers/profile.js:67]: also can be removed

File: theseus_gui/src/helpers/utils.js [hunk 4]
```diff
@@ -35,7 +36,14 @@ export const releaseColor = (releaseType) => {
...
 
 export const installVersionDependencies = async (profile, version) => {
+  const duplicates = await check_duplicate_nonversional_dependencies(
+    profile.path,
+    version.dependencies
+  )
   for (const dep of version.dependencies) {
+    // if duplicates has a version that matches, skip
+    if (duplicates.find((d) => d.version_id === dep.version_id)) continue
+
```
Comment (Geometrically) [inline theseus_gui/src/helpers/utils.js:46]: can be removed

File: theseus_gui/src/helpers/utils.js [hunk 5]
```diff
@@ -35,7 +36,14 @@ export const releaseColor = (releaseType) => {
 }
 
 export const installVersionDependencies = async (profile, version) => {
+  const duplicates = await check_duplicate_nonversional_dependencies(
+    profile.path,
+    version.dependencies
+  )
```
Comment (Geometrically) [inline theseus_gui/src/helpers/utils.js:42]: can be removed

File: theseus_gui/src/pages/Browse.vue [hunk 6]
```diff
@@ -394,11 +386,10 @@ async function clearFilters() {
   for (const facet of [...orFacets.value]) {
     await toggleOrFacet(facet, true)
   }
-
   onlyOpenSource.value = false
   selectedVersions.value = []
   selectedEnvironments.value = []
-  await onSearchChange(1)
+  await onSearchChangeToTop(1)
```
Comment (Geometrically) [inline theseus_gui/src/pages/Browse.vue:392]: why were these and others changed to to top? these operations should not affect the scroll pos

File: theseus_gui/src/pages/instance/Mods.vue [hunk 7]
```diff
@@ -769,10 +770,17 @@ watch(selectAll, () => {
...
+    await install_from_file(event.payload[0]).catch(handleError)
+    mixpanel.track('InstanceCreate', {
+      source: 'FileDrop',
+    })
+  } else {
+    for (const file of event.payload) {
+      await add_project_from_path(props.instance.path, file, 'mod').catch(handleError)
+    }
+    initProjects(await get(props.instance.path).catch(handleError))
   }
```
Comment (Geometrically) [inline theseus_gui/src/pages/instance/Mods.vue:783]: mixpanel needs to be added in this else statement as well, or at least moved out of this

**Review by Geometrically — CHANGES_REQUESTED** [review]

**Review by Geometrically — APPROVED** [review]
